{
    "ok": True,
    'bienes': {'muebles': [{"bien": "Vehiculo",
                            "tipo": "",
                            "descripcion": "",
                            "caracteristicas": "",
                            "valor": 0}],
               'inmuebles': [{'valor': 4808,
                              'registro': u'0000129094',
                              'tipo': u'LOCAL STAND 13 (12.5%)',
                              'direccion': u'AV. LA PAZ 646 MIRAFLORES'}]},
    'otraExperiencia': [{"cargo": "",
                          "entidad": "",
                          "inicio": 0,
                          "fin": 0}],
    'militancia': [{'fin': 2009,
                    'orgPolitica': u'Partido por la Democracia Social - Compromiso Per\xfa',
                    'inicio': 2001}],
    'civil': [{"materia": "",
               "expediente": "",
               "juzgado": "",
               "materia": "",
               "fallo": "",}],
    'educacionSuperior': {'postgrado': [{'concluido': 1,
                                       'gradoTitulo': u'',
                                       'tipo': None,
                                       'inicio': 1966,
                                       'pais': u'PER\xda',
                                       'instEducativa': u'Instituto Superior de Educaci\xf3n Familiar',
                                       'fin': 1970,
                                       'especialidad': u'Educadora Familiar'}],
                          'tecnico': [{'concluido': 1,
                                     'provincia': u'LIMA',
                                     'curso': u'Educaci\xf3n Familiar',
                                     'distrito': u'MIRAFLORES',
                                     'especialidad': u'Educadora Familiar',
                                     'departamento': u'LIMA',
                                     'inicio': 1966,
                                     'pais': u'PER\xda',
                                     'instEducativa': u'Instituto Superior de Educaci\xf3n Familiar',
                                     'fin': 1970}],
                          'universitario': [{'departamento': None,
                                           'pais': u'CHILE',
                                           'concluido': 0,
                                           'gradoTitulo': u'Ninguno',
                                           'provincia': None,
                                           'fin': None,
                                           'facultad': u'SOCIOLOGIA',
                                           'carrera': u'SOCIOLOGIA',
                                           'inicio': 1973,
                                           'instEducativa': u' UNIVERSIDAD CAT\xd3LICA DE CHILE',
                                           'distrito': None}]},
    'observaciones': [{"referencia": "",
                       "anotacion": ""}],
    'partidario': [{'cargo': u'Primera y Segunda Vicepresidente',
                    'ambito': u'NACIONAL',
                    'fin': 2010,
                    'orgPolitica': u'Partido Descentralista Fuerza Social',
                    'inicio': 2008}],
    'eleccion': [{'procesoElectoral': u'2010',
                  'cargo': u'ALCALDE PROVINCIAL',
                  'provincia': u'LIMA',
                  'departamento': u'LIMA',
                  'inicio': 2011,
                  'fin': None,
                  'distrito': None,
                  'ambito': u'PROVINCIAL',
                  'orgPolitica': u'Partido Descentralista Fuerza Social'}],
    'ingresos': {'remuneracion': {'publico': 14300,
                                  'total': 14300,
                                  'privado': 0},
                 'total': 15754.6,
                 'otros': {'publico': 0,
                           'total': 1454.6,
                           'privado': 1454.6},
                 'renta': {'publico': 0,
                           'total': 0,
                           'privado': 0}},
    'experiencia': [{'sector': u'P\xfablico',
                     'cargo': 2011,
                     'provincia': u'LIMA',
                     'empleador': u'Municipalidad Metropolitana de Lima',
                     'inicio': 2011,
                     'distrito': u'LIMA',
                     'fin': 'AHORA',
                     'departamento': u'LIMA'}],
    'educacionBasica': {'secundaria': [{'concluido': 1,
                                        'provincia': u'LIMA',
                                        'distrito': u'SANTIAGO DE SURCO',
                                        'departamento': u'LIMA',
                                        'inicio': 1961,
                                        'pais': u'PER\xda',
                                        'instEducativa': u'Sagrado Coraz\xf3n Monterrico',
                                        'fin': 1962}],
                        'primaria': [{'concluido': 1,
                                      'provincia': u'LIMA',
                                      'distrito': u'CHORRILLOS',
                                      'departamento': u'LIMA',
                                      'inicio': 1955,
                                      'pais': u'PER\xda',
                                      'instEducativa': u'SAGRADO CORAZON CHALET',
                                      'fin': 1960}]},
    'familia': {'madre': u'JOSEFINA DE LA PUENTE Y LAVALLE',
                'conyuge': u'MANUEL EDUARDO JORGE PIQUERAS LUNA',
                'padre': u'FERNANDO VILLARAN DUANY'},
    'acreencias': [{'monto': 3465,
                    'detalle': u'Caja Metropolitana de Lima'}],
    'penal': [{"expediente": "",               
               "fechaSentencia": "",
               "juzgado": "",
               "delito": "",
               "fallo": ""}],
    '_id': 104272,
    'postulacion': {'cargo': u'ALCALDE PROVINCIAL',
                    'distrito': u'',
                    'provincia': u'LIMA',
                    'departamento': u'LIMA',
                    'designacion': u'NO OBLIGATORIO PARA ORGANIZACION POLITICA LOCAL PROVINCIAL O DISTRITAL'},
    'nacimiento': {'pais': u'PER\xda',
                   'fecha': u'61/80/9491',
                   'distrito': u'LIMA',
                   'provincia': u'LIMA',
                   'departamento': u'LIMA'},
    'datosPersonales': {'apellidoMaterno': u'VILLARAN',
                        'nombres': u'SUSANA MARIA DEL CARMEN',
                        'dni': 8051943,
                        'sexo': 'F',
                        'apellidoPaterno': u'VILLARAN',
                        'email': u'susanavillaran2014@gmail.com'},
    'residencia': {'lugar': u'Calle Bertolotto 111 dpto. 711',
                   'distrito': u'SAN MIGUEL',
                   'tiempo': u'63',
                   'provincia': u'LIMA',
                   'departamento': u'LIMA'}
}
