{
'bienes': {'muebles': None,
            'inmuebles': [{'valor': 4808,
                           'registro': u'0000129094',
                           'tipo': u'LOCAL STAND 13 (12.5%)',
                           'direccion': u'AV. LA PAZ 646 MIRAFLORES'},
                          {'valor': 54569,
                           'registro': u'0000129103',
                           'tipo': u'LOCAL STAND B (12.5%)',
                           'direccion': u'AV. LA PAZ 646 MIRAFLORES'},
                          {'valor': 28968,
                           'registro': u'0000129102',
                           'tipo': u'LOCAL STAND 20 (12.5%)',
                           'direccion': u'AV. LA PAZ 646 MIRAFLORES'},
                          {'valor': 32683,
                           'registro': u'0000129095',
                           'tipo': u'LOCAL STAND 14 ',
                           'direccion': u'AV. LA PAZ 646 MIRAFLORES'},
                          {'valor': 23720,
                           'registro': u'0000129096',
                           'tipo': u'Local stand 15 ',
                           'direccion': u'Av. La Paz 646 Miraflores'},
                          {'valor': 6325,
                           'registro': u'0000129104',
                           'tipo': u'Local stand 21 (12.5%)',
                           'direccion': u'Av. La Paz 646 Miraflores'},
                          {'valor': 19750,
                           'registro': u'0000129098',
                           'tipo': u'Local stand 16 (12.5%)',
                           'direccion': u'Av. La Paz 646 Miraflores'},
                          {'valor': 28872,
                           'registro': u'0000129093',
                           'tipo': u'LOCAL STAND 12',
                           'direccion': u'AV. LA PAZ 646 MIRAFLORES'},
                          {'valor': 25831,
                           'registro': u'0000129101',
                           'tipo': u'LOCAL STAND 19 (12.5%)',
                           'direccion': u'AV. LA  PAZ 646 MIRAFLORES'},
                          {'valor': 11445,
                           'registro': u'0000129100',
                           'tipo': u'LOCAL STAND 18 (12.5%)',
                           'direccion': u'AV. LA PAZ 646 MIRAFLORES'},
                          {'valor': 14503,
                           'registro': u'0000129099',
                           'tipo': u'LOCAL STAND 17  (12,5%)',
                           'direccion': u'AV. LA PAZ 646 MIRAFLORES'},
                          {'valor': 1606,
                           'registro': u'0000129097',
                           'tipo': u'LOCAL STAND 12A (12.5%)',
                           'direccion': u'AV. LA  PAZ 646 MIRAFLORES'},
                          {'valor': 1895,
                           'registro': u'0000129105',
                           'tipo': u'LOCAL STAND 22 (12.5%)',
                           'direccion': u'AV LA PAZ 646 MIRAFLORES'}]},
 'otra_experiencia': None,
 'militancia': [{'fin': 2009,
                 'orgPolitica': u'Partido por la Democracia Social - Compromiso Per\xfa',
                 'inicio': 2001},
                {'fin': None,
                 'orgPolitica': u'Partido Descentralista Fuerza Social',
                 'inicio': 2010}],
 'civil': None,
 'educacion_superior': {'postgrado': [{'concluido': 1,
                                       'gradoTitulo': u'',
                                       'tipo': None,
                                       'inicio': 1966,
                                       'pais': u'PER\xda',
                                       'instEducativa': u'Instituto Superior de Educaci\xf3n Familiar',
                                       'fin': 1970,
                                       'especialidad': u'Educadora Familiar'},
                                      {'concluido': 1,
                                       'gradoTitulo': u'Ninguno',
                                       'tipo': u'Curso de Especializaci\xf3n',
                                       'inicio': 1972,
                                       'pais': u'Chile',
                                       'instEducativa': u'Universidad Cat\xf3lica de Chile',
                                       'fin': 1972,
                                       'especialidad': u'Centro de Estudios para la Realidad Nacional'}],
                        'tecnico': [{'concluido': 1,
                                     'provincia': u'LIMA',
                                     'curso': u'Educaci\xf3n Familiar',
                                     'distrito': u'MIRAFLORES',
                                     'especialidad': u'Educadora Familiar',
                                     'departamento': u'LIMA',
                                     'inicio': 1966,
                                     'pais': u'PER\xda',
                                     'instEducativa': u'Instituto Superior de Educaci\xf3n Familiar',
                                     'fin': 1970}],
                        'universitario': [{'departamento': None,
                                           'pais': u'CHILE',
                                           'concluido': 0,
                                           'gradoTitulo': u'Ninguno',
                                           'provincia': None,
                                           'fin': None,
                                           'facultad': u'SOCIOLOGIA',
                                           'carrera': u'SOCIOLOGIA',
                                           'inicio': 1973,
                                           'instEducativa': u' UNIVERSIDAD CAT\xd3LICA DE CHILE',
                                           'distrito': None},
                                          {'departamento': u'LIMA',
                                           'pais': u'PER\xda',
                                           'concluido': 0,
                                           'gradoTitulo': u'Ninguno',
                                           'provincia': u'LIMA',
                                           'fin': None,
                                           'facultad': u'PERIODISMO',
                                           'carrera': u'PERIODISMO',
                                           'inicio': 1980,
                                           'instEducativa': u'JAIME BAUSATE Y MEZA',
                                           'distrito': u'JESUS MARIA'}]},
 'observaciones': None,
 'partidario': [{'cargo': u'Primera y Segunda Vicepresidente',
                 'ambito': u'NACIONAL',
                 'fin': 2010,
                 'orgPolitica': u'Partido Descentralista Fuerza Social',
                 'inicio': 2008},
                {'cargo': u'Coordinadora Nacional',
                 'ambito': u'NACIONAL',
                 'fin': 2001,
                 'orgPolitica': u'Partido por la Democracia Social - Compromiso Per\xfa',
                 'inicio': 2000},
                {'cargo': u'Miembro y Coordinadora de la Comisi\xf3n Pol\xedtica',
                 'ambito': u'NACIONAL',
                 'fin': 2008,
                 'orgPolitica': u'Partido por la Democracia Social - Compromiso Per\xfa',
                 'inicio': 2002}],
 'eleccion': [{'procesoElectoral': u'2010',
               'cargo': u'ALCALDE PROVINCIAL',
               'provincia': u'LIMA',
               'departamento': u'LIMA',
               'inicio': 2011,
               'fin': None,
               'distrito': None,
               'ambito': u'PROVINCIAL',
               'orgPolitica': u'Partido Descentralista Fuerza Social'}],
 'ingresos': {'remuneracion': {'publico': 14300,
                               'total': 14300,
                               'privado': 0},
              'total': 15754.6,
              'otros': {'publico': 0,
                        'total': 1454.6,
                        'privado': 1454.6},
              'renta': {'publico': 0,
                        'total': 0,
                        'privado': 0}},
 'experiencia': [{'sector': u'P\xfablico',
                  'cargo': 2011,
                  'provincia': u'LIMA',
                  'empleador': u'Municipalidad Metropolitana de Lima',
                  'inicio': 2011,
                  'distrito': u'LIMA',
                  'fin': 'AHORA',
                  'departamento': u'LIMA'},
                 {'sector': u'P\xfablico',
                  'cargo': 2002,
                  'provincia': u'LIMA',
                  'empleador': u'Ministerio del Interior',
                  'inicio': 2002,
                  'distrito': u'SAN ISIDRO',
                  'fin': 2003,
                  'departamento': u'LIMA'},
                 {'sector': u'P\xfablico',
                  'cargo': 2000,
                  'provincia': u'LIMA',
                  'empleador': u'Ministerio de Promoci\xf3n de la Mujer y Desarrollo Humano',
                  'inicio': 2000,
                  'distrito': u'LIMA',
                  'fin': 2001,
                  'departamento': u'LIMA'}],
 'educacion_basica': {'secundaria': [{'concluido': 1,
                                      'provincia': u'LIMA',
                                      'distrito': u'SANTIAGO DE SURCO',
                                      'departamento': u'LIMA',
                                      'inicio': 1961,
                                      'pais': u'PER\xda',
                                      'instEducativa': u'Sagrado Coraz\xf3n Monterrico',
                                      'fin': 1962}],
                      'primaria': None},
 'familia': {'madre': u'JOSEFINA DE LA PUENTE Y LAVALLE',
             'conyuge': u'MANUEL EDUARDO JORGE PIQUERAS LUNA',
             'padre': u'FERNANDO VILLARAN DUANY'},
 'acreencias': [{'monto': 3465,
                 'detalle': u'Caja Metropolitana de Lima'},
                {'monto': 111200,
                 'detalle': u'BBVA Cr\xe9dito hipotecario'}],
 'penal': None,
 'id': 104272,
 'principal': {'postulacion': {'cargo': u'ALCALDE PROVINCIAL',
                               'distrito': u'',
                               'provincia': u'LIMA',
                               'departamento': u'LIMA',
                               'designacion': u'NO OBLIGATORIO PARA ORGANIZACION POLITICA LOCAL PROVINCIAL O DISTRITAL'},
               'nacimiento': {'pais': u'PER\xda',
                              'fecha': u'61/80/9491',
                              'distrito': u'LIMA',
                              'provincia': u'LIMA',
                              'departamento': u'LIMA'},
               'datosPersonales': {'apellidoMaterno': u'VILLARAN',
                                   'nombres': u'SUSANA MARIA DEL CARMEN',
                                   'dni': 8051943,
                                   'sexo': 'F',
                                   'apellidoPaterno': u'VILLARAN',
                                   'email': u'susanavillaran2014@gmail.com'},
               'residencia': {'lugar': u'Calle Bertolotto 111 dpto. 711',
                              'distrito': u'SAN MIGUEL',
                              'tiempo': u'63',
                              'provincia': u'LIMA',
                              'departamento': u'LIMA'}}
}
